<header>
  <nav id="component-id">
    <div class="nav-container">
      <a class="nav-logo" href="index.php">NETFLOW</a>
      <div class="nav-links">
        <a href="manager_login.php">Login as Staff</a>
        <a href="index.php">Home</a>
        <a href="product.php">Products</a>
        <a href="enquire.php">Enquire</a>
        <a href="about.php">About</a>
        <a href="enhancements.php">Enhancements</a>
        <a href="enhancements_2.php">Enhancements 2</a>
        <a href="enhancements_3.php">Enhancements 3</a>
      </div>
    </div>
  </nav>
</header>
